import Head from "next/head";
import Link from "next/link";
import { ProductCard } from "~/domain/product/components/product-card/product-card";
import { Button } from "~/_shared/components/Button";
import { Header } from "~/_shared/components/Header";
import { api } from "~/utils/api";
import { Container } from "~/_shared/components/Container";
import { useRouter } from "next/router";

export default function Home() {
  const { data, isLoading } = api.product.getAll.useQuery();
  const router = useRouter();
  if (isLoading) return <h1>Is loading...</h1>;
  if (!data) return <h1>No data</h1>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          type="page"
          className="flex min-h-screen flex-col  justify-center p-4 px-7 pt-24"
        >
          <Header />
          <div className="grid grid-cols-1 gap-7 sm:grid-cols-2 md:grid-cols-3">
            {data.map((product) => (
              <ProductCard
                id={product.id}
                key={product.id}
                product={product}
                image={
                  <ProductCard.Image
                    onClick={() => {
                      void router.replace(`products/${product.id}`);
                    }}
                  />
                }
                body={
                  <>
                    <ProductCard.Title />
                    <ProductCard.Description />
                  </>
                }
                actions={
                  <>
                    <ProductCard.Price />
                    <Button>Buy now</Button>
                  </>
                }
              />
            ))}
          </div>
        </Container>
      </main>
    </>
  );
}
